name: build

env:
  GO_VERSION: 1.14
  NODE_VERSION: 13
  AG_VERSION: v0.103.3

on:
  push:
    branches:
      - 'master'

jobs:

  app:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: AdguardTeam/AdGuardHome
          ref: ${{ env.AG_VERSION }}
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      -
        name: Set up Go modules cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      -
        name: Set up node_modules cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      -
        name: Set up Snapcraft
        run: |
          sudo apt-get -yq --no-install-suggests --no-install-recommends install snapcraft
      -
        name: Set up GoReleaser
        run: |
          curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | BINDIR="$(go env GOPATH)/bin" sh
      -
        name: Run snapshot build
        run: |
          CHANNEL=release make release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/AdGuardHome_darwin_386.zip
            dist/AdGuardHome_darwin_amd64.zip
            dist/AdGuardHome_freebsd_386.tar.gz
            dist/AdGuardHome_freebsd_amd64.tar.gz
            dist/AdGuardHome_freebsd_arm64.tar.gz
            dist/AdGuardHome_freebsd_armv5.tar.gz
            dist/AdGuardHome_freebsd_armv6.tar.gz
            dist/AdGuardHome_freebsd_armv7.tar.gz
            dist/AdGuardHome_linux_386.tar.gz
            dist/AdGuardHome_linux_amd64.tar.gz
            dist/AdGuardHome_linux_arm64.tar.gz
            dist/AdGuardHome_linux_armv5.tar.gz
            dist/AdGuardHome_linux_armv6.tar.gz
            dist/AdGuardHome_linux_armv7.tar.gz
            dist/AdGuardHome_linux_mips64_softfloat.tar.gz
            dist/AdGuardHome_linux_mips64le_softfloat.tar.gz
            dist/AdGuardHome_linux_mips_softfloat.tar.gz
            dist/AdGuardHome_linux_mipsle_softfloat.tar.gz
            dist/AdGuardHome_windows_386.zip
            dist/AdGuardHome_windows_amd64.zip
          draft: true
          name: ${{ env.AG_VERSION }}
          tag_name: ${{ env.AG_VERSION }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
